data$SP.Chg= with(data,(SPClose-SPOpen)/SPOpen)
mean(SPOpen,SPClose)
data$Nik.Chg= with(data,(NikClose-NikOpen)/NikOpen)
filter(data,SP.Chg-Nik.Chg>0.10)
filter(data,abs(SP.Chg-Nik.Chg)>.10)
data$Nas.Chg= with(data,(NasClose-NasOpen)/SPOpen)
data$FTSE.Chg= with(data,(FTSEClose-FTSEOpen)/FTSEOpen)
data$DAX.Chg= with(data, (DAXClose-DAXOpen)/DAXOpen)
data$HS.Chg= with(data, (HSClose-HSOpen)/HSOpen)
data$SP.avg= with(data, ((SPHigh-SPLow)/2))
rename(data, c("SP.Chg"="SPchg","Nas.Chg"="Naschg","FTSE.Chg"="FTSEchg","DAX.Chg"="DAXchg","Nik.Chg"="NIKchg","HS.Chg"="HSchg","NikOpen"="NIKOpen","Nikclose"="NIKClose","NikHigh"="NIKHigh","NikLow"="NIKLow"))
data$SPsd <- with(data, sqrt(((SPHigh-SPavg)^2+(SPLow-SPavg)^2)/2)) 
data$SPv <- with(data, SPsd/SPavg)
